"""is_active not nullable

Revision ID: 5360c2c86946
Revises: 991763651360
Create Date: 2024-01-28 15:56:29.077701

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5360c2c86946"
down_revision: Union[str, None] = "991763651360"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.execute("UPDATE users SET is_active = false WHERE is_active IS NULL")
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=True)

    # ### end Alembic commands ###
